import type { Metadata } from "next";

import "./globals.css";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let items = [
  { name: "Compromiso", link: "/" },
  { name: "Diamantes", link: "/" },
  { name: "Contacto", link: "/" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-myWhite">
        <header>
          <Nav
            elements={items}
            whatsapp={
              "https://api.whatsapp.com/send/?phone=5930983883197&text=Hola,%20vi%20su%20página%20y%20deseo%20información%20sobre%20sus%20anillos"
            }
          />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
